from django.urls import path
from .views import (
    index,
    about,
    read_categories,
    post_category,
    update_category,
    delete_category,
    read_expenses_by_category,
    read_receipts,
    post_receipt,
    update_receipt,
    delete_receipt,
    read_receipt,
    post_expense,
    update_expense,
    delete_expense,
    personal_statistics,
    statistics_groups,
    group_statistics,
)

app_name = 'expenses'

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('categories/', read_categories, name='categories'),
    path('categories/post_category/', post_category, name='post_category'),
    path('categories/<int:category_pk>/update_category/', update_category, name='update_category'),
    path('categories/<int:category_pk>/delete_category/', delete_category, name='delete_category'),
    path('categories/<int:category_pk>/expenses', read_expenses_by_category, name='read_expenses_by_category'),
    path('receipts/', read_receipts, name='receipts'),
    path('receipts/post_receipt/', post_receipt, name='post_receipt'),
    path('receipts/<int:receipt_pk>/update_receipt/', update_receipt, name='update_receipt'),
    path('receipts/<int:receipt_pk>/delete_receipt/', delete_receipt, name='delete_receipt'),
    path('receipts/<int:receipt_pk>/', read_receipt, name='read_receipt'),
    path('receipts/<int:receipt_pk>/expenses/post_expense/', post_expense, name='post_expense'),
    path('receipts/<int:receipt_pk>/expenses/<int:expense_pk>/update_expense/', update_expense,
         name='update_expense'),
    path('receipts/<int:receipt_pk>/expenses/<int:expense_pk>/delete_expense/', delete_expense,
         name='delete_expense'),
    path('statistics/personal/', personal_statistics, name='personal_statistics'),
    path('statistics/groups/', statistics_groups, name='statistics_groups'),
    path('statistics/groups/<int:group_pk>/', group_statistics, name='group_statistics'),
]
