services:
  web:
    build: .
    volumes:
      - static_volume:/app/static
    networks:
      - backend
    expose:
      - "8000"

  nginx:
    image: nginx:1.26.3
    volumes:
      - nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend

volumes:
  static_volume:

networks:
  backend:
    driver: bridge
